import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'mr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
  speak: (text: string, langOverride?: Language) => void;
  stopSpeaking: () => void;
  isSpeaking: boolean;
  formatCurrency: (amount: number) => string;
  preserveEnglishItemName: (name: string) => string;
}

// Known scrap item names being sold — MUST ONLY EVER BE SHOWN IN ENGLISH as requested
const KNOWN_ENGLISH_SCRAP_ITEMS: Record<string, string> = {
  'Printed Circuit Boards (PCBs)': 'Printed Circuit Boards (PCBs)',
  'High-Grade Server PCBs': 'High-Grade Server PCBs',
  'High-grade PCB (Motherboards/Servers)': 'High-grade PCB (Motherboards/Servers)',
  'High-grade PCB (Motherboard/RAM)': 'High-grade PCB (Motherboard/RAM)',
  'High-grade Printed Circuit Boards (PCBs)': 'High-grade Printed Circuit Boards (PCBs)',
  'Low-grade PCB (Consumer Electronics)': 'Low-grade PCB (Consumer Electronics)',
  'Low-grade PCB (Power Supplies/TV)': 'Low-grade PCB (Power Supplies/TV)',
  'Copper Cables & Insulated Wires': 'Copper Cables & Insulated Wires',
  'Clean Peeled Copper Wire': 'Clean Peeled Copper Wire',
  'Clean Copper Wire (Bright Strip)': 'Clean Copper Wire (Bright Strip)',
  'Copper Wiring (Clean Bright)': 'Copper Wiring (Clean Bright)',
  'Lithium-ion Batteries': 'Lithium-ion Batteries',
  'Lithium-ion Battery Packs': 'Lithium-ion Battery Packs',
  'Lithium-ion Batteries (Laptop/EV)': 'Lithium-ion Batteries (Laptop/EV)',
  'Li-ion Batteries (Laptops/EV)': 'Li-ion Batteries (Laptops/EV)',
  'Electric Motors & Magnets': 'Electric Motors & Magnets',
  'Electric Motors & Transformer Coils': 'Electric Motors & Transformer Coils',
  'CRT Monitor Glass Unit': 'CRT Monitor Glass Unit',
  'CRT Monitor Glass (Treated)': 'CRT Monitor Glass (Treated)',
  'CRT Glass (Funnel Treated)': 'CRT Glass (Funnel Treated)',
  'LCD/LED Display Panels': 'LCD/LED Display Panels',
  'LCD & LED Display Panels': 'LCD & LED Display Panels',
  'Engineering E-Plastics (ABS/HIPS)': 'Engineering E-Plastics (ABS/HIPS)',
  'Engineering Plastics (ABS/HIPS)': 'Engineering Plastics (ABS/HIPS)',
  'Smartphones & Tablets': 'Smartphones & Tablets',
  'Server Grade Motherboards': 'Server Grade Motherboards',
  'Telecom Relay Units': 'Telecom Relay Units',
  'Lead Acid Batteries': 'Lead Acid Batteries',
  'Aluminium Heat Sinks': 'Aluminium Heat Sinks',
  'Brass Transformers': 'Brass Transformers',
  'Power Supply Units (SMPS)': 'Power Supply Units (SMPS)',

  // Reverse mapping for Hindi & Marathi names to guarantee strict English display
  'हाई-ग्रेड सर्किट बोर्ड (मदरबोर्ड/रैम)': 'High-grade PCB (Motherboard/RAM)',
  'हाय-ग्रेड सर्किट बोर्ड (मदरबोर्ड/रॅम)': 'High-grade PCB (Motherboard/RAM)',
  'साफ तांबा तार (ब्राइट छिला हुआ)': 'Clean Copper Wire (Bright Strip)',
  'स्वच्छ तांब्याची तार (सोलेली)': 'Clean Copper Wire (Bright Strip)',
  'लो-ग्रेड सर्किट बोर्ड (पावर सप्लाई/टीवी)': 'Low-grade PCB (Power Supplies/TV)',
  'लो-ग्रेड सर्किट बोर्ड (टीव्ही/पॉवर सप्लाय)': 'Low-grade PCB (Power Supplies/TV)',
  'लिथियम-आयन बैटरियां (लैपटॉप/ईवी)': 'Lithium-ion Batteries (Laptop/EV)',
  'लिथियम-आयन बॅटऱ्या (लॅपटॉप/ईव्ही)': 'Lithium-ion Batteries (Laptop/EV)',
  'इलेक्ट्रिक मोटर और चुंबक': 'Electric Motors & Magnets',
  'इलेक्ट्रिक मोटर आणि चुंबक': 'Electric Motors & Magnets',
  'एलसीडी और एलईडी डिस्प्ले पैनल': 'LCD/LED Display Panels',
  'एलसीडी आणि एलईडी डिस्प्ले पॅनेल्स': 'LCD/LED Display Panels',
  'मिश्रित ई-प्लास्टिक (ABS/HIPS)': 'Engineering E-Plastics (ABS/HIPS)',
  'सीआरटी कांच (लीड उपचारित)': 'CRT Monitor Glass Unit',
  'सीआरटी काच (लेड प्रक्रिया)': 'CRT Monitor Glass Unit',
  'PCBs': 'Printed Circuit Boards (PCBs)',
  'Batteries': 'Lithium-ion Batteries',
  'Cables': 'Copper Cables & Insulated Wires',
  'CRT Screens': 'CRT Monitor Glass Unit',
  'PCBs & Logic Boards': 'Printed Circuit Boards & Logic Boards',
  'Copper Cables & Winding': 'Copper Cables & Winding',
  'Li-ion Batteries': 'Lithium-ion Batteries',
  'CRT Monitor Glass': 'CRT Monitor Glass Unit',
  'Engineering E-Plastics': 'Engineering E-Plastics (ABS/HIPS)'
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    appName: 'Kabadiwala Connect',
    tagline: 'e-Waste Traceability & EPR Exchange',
    dhatuTag: 'Dhatu — e-Waste Traceability & Formalization',
    dhatuSub: 'Smart Informal Scrap & Formal Recycler Ecosystem',
    sihBadge: 'SIH26229',
    sihSub: 'Ministry of Mines — Informal e-Waste Integration',
    activeTerminal: 'Active Terminal',
    switchRole: 'Switch Role Portal',
    signIn: 'Sign In',
    signInBtn: 'Sign In to Dedicated Portal',
    signOut: 'Sign Out',
    langSelect: 'Change Language',
    selectLanguage: 'Select Language',
    listen: 'Listen aloud',
    stop: 'Stop audio',
    initializing: 'Initializing Dhatu Ecosystem...',

    portalCitizen: 'Citizen Portal',
    portalCollector: 'Collector Portal',
    portalRecycler: 'Authorized Recycler',
    portalAdmin: 'Admin & CPCB Audit',
    roleCitizen: 'Citizen & Household',
    roleCollector: 'Doorstep Scrap Collector',
    roleRecycler: 'Authorized Recycler',
    roleAdmin: 'Admin & Regulatory Audit',
    personaCitizen: 'Ramesh Sharma',
    personaCollector: 'Suresh Kumar',
    personaRecycler: 'EcoRecycle Aggregators Ltd',
    personaAdmin: 'NDMC Waste & Mines Cell',

    heroTitle: "Dhatu — Digital Traceability & EPR Exchange for India's e-Waste Economy",
    heroSubtitle: "Bridging informal door-to-door scrap collectors with formal CPCB smelters. Built on a low-literacy, offline-tolerant passbook architecture with verifiable digital handovers.",
    roleBasedLogin: 'Role-Based Sign In',
    sourcingLayer: 'Sourcing Layer (Ramesh)',
    coreAsk: 'CORE SIH26229 ASK',
    formalSide: 'FORMAL INTERFACE',
    regulatoryLayer: 'REGULATORY DATA LAYER',
    citizenCardDesc: 'Request doorstep e-waste pickup, instant indicative price estimates, live collector tracking & CSR tree donation.',
    collectorCardDesc: 'Low-literacy lot creation, spoken price board, QR handover generation, passbook running ledger & safety cards.',
    recyclerCardDesc: 'Incoming collector lot review, QR scan verification, live price broadcasting, and CPCB Form-2/6 filings.',
    adminCardDesc: 'Citywide tonnage analytics, 4-stage material traceability dataset with SHA-256 hashes & KYC approvals.',
    enterAsCitizen: 'Enter as Citizen',
    enterAsCollector: 'Enter as Collector',
    enterAsRecycler: 'Enter as Recycler',
    enterAsAdmin: 'Enter as Admin',

    authGateway: 'Role-Based Authentication Gateway',
    selectRole: 'Select Your Role',
    loginSubtitle: "Kabadiwala Connect provides a dedicated, purpose-built interface for each stakeholder in India's formal e-waste chain.",
    instantLogin: '1-Click Instant Login as',
    orCredentials: 'Or Enter Credentials',
    mobileNumber: 'Mobile Number',
    cpcbRegNumber: 'CPCB Facility Reg Number / Mobile',
    password: 'Password or PIN',
    submitLogin: 'Submit & Open Dashboard',
    dedicatedFeatures: 'Dedicated Features for this Portal',
    activeTabBadge: 'ACTIVE',

    status: 'Status',
    actions: 'Actions',
    submit: 'Submit',
    cancel: 'Cancel',
    save: 'Save',
    back: 'Back',
    delete: 'Delete',
    loading: 'Loading...',
    verified: 'VERIFIED',
    pending: 'PENDING',
    completed: 'COMPLETED',
    assigned: 'ASSIGNED',
    inProgress: 'IN PROGRESS',
    requested: 'REQUESTED',
    accepted: 'ACCEPTED',
    rejected: 'REJECTED',
    viewDetails: 'View Details',
    close: 'Close',
    date: 'Date',
    weight: 'Weight',
    amount: 'Amount',
    total: 'Total',
    ratePerKg: 'Rate per kg',
    perKg: 'per kg',
    estValue: 'Estimated Value',
    mandiRate: 'Mandi Benchmark Rate',
    itemMaterial: 'Item / Material',

    tabMyPickups: 'My Pickups',
    tabSchedulePickup: 'Schedule Pickup',
    tabImpact: 'Landfill Impact & Trees',
    tabDropoff: 'Drop-Off Centers',
    pickupAddress: 'Pickup Address',
    scheduledTime: 'Scheduled Date & Time',
    notesCarton: 'Notes & Description',
    itemsToRecycle: 'E-Waste Items to Recycle',
    addMoreItems: 'Add Item',
    scanAiPhoto: 'Scan Scrap with AI Camera',
    indicativePriceRange: 'Indicative Price Range',
    confirmPickup: 'Confirm & Request Pickup',
    collectorTracking: 'Collector On The Way',
    collectorEta: 'Estimated Arrival: 12 mins',
    viewReceipt: 'View Verifiable Receipt',
    downloadCert: 'Download Safe Disposal Certificate',
    csrDonationNote: 'Donate value to Green Earth NGO to plant trees',
    treesPlanted: 'Trees Planted via Diversion',
    landfillDivertedKg: 'kg Diverted from Landfills',
    dropoffTitle: 'Authorized E-Waste Drop-Off Centers',

    tabLots: 'My Lots',
    tabPriceBoard: 'Spoken Price Board',
    tabFindRecyclers: 'Nearby Recyclers',
    tabHandover: 'Generate QR',
    tabPassbook: 'Cash Passbook',
    tabSafety: 'Safety Guidance',
    createLot: 'Create New Lot',
    selectScrapCategory: 'Select Item Category',
    lotWeightKg: 'Lot Weight (kg)',
    takePhotoProof: 'Take Photo Proof',
    saveLot: 'Save Lot to Ledger',
    listenPriceAloud: 'Listen to Price Aloud',
    todayMandiRate: "Today's Mandi Benchmark Rate",
    passbookBalance: 'Passbook Balance',
    cashCollected: 'Total Cash Collected',
    totalSoldLots: 'Total Lots Dispatched',
    runningLedger: 'Cash & Lot Transaction Ledger',
    credit: 'Credit (+)',
    debit: 'Debit (-)',
    balance: 'Balance',
    offlineTolerant: 'Offline Mode Active (Zero Internet Needed)',
    syncPending: 'Lots Pending Sync',
    syncNow: 'Sync Now',
    safetyRulesTitle: 'Pictorial & Spoken Safety Cards',

    tabIncoming: 'Incoming Lots',
    tabVerifyQr: 'Verify Handover QR',
    tabRateConsole: 'Buying Rate Console',
    tabAnomalies: 'AI Anomaly Audit',
    tabReports: 'CPCB EPR Reports',
    tabFacility: 'Facility Profile',
    lotCode: 'Lot Code',
    collectorName: 'Collector',
    approxWeight: 'Approx Weight (kg)',
    offeredRate: 'Offered Rate (₹/kg)',
    totalAmount: 'Total Amount',
    acceptLot: 'Accept Lot',
    rejectLot: 'Reject Lot',
    counterOffer: 'Counter Rate',
    broadcastRates: 'Broadcast Rates to All Collectors',
    downloadForm2: 'Download CPCB Form-2 (JSON)',
    downloadForm6: 'Download CPCB Form-6 (CSV)',
    facilityRegStatus: 'CPCB EPR Registration Active',

    tabOverview: 'Citywide Overview',
    tabTraceability: 'Material Traceability Chain',
    tabUnitEconomics: 'Unit-Economics Calculator',
    tabVerifications: 'Collector KYC Verifications',
    tabEpr: 'CPCB 2022 Schema Export',
    citywideTonnage: 'Total E-Waste Diverted',
    activeCollectors: 'Registered Formalized Collectors',
    authorizedSmelters: 'CPCB Authorized Facilities',
    monthlyVolume: 'Monthly Collector Volume (kg)',
    middlemanCut: 'Informal Middleman Cut Eliminated',
    incomeBoost: 'Net Income Boost for Collector',
    approveKyc: 'Approve & Issue Badge',
    rejectKyc: 'Reject',
    traceabilityTitle: 'End-to-End 4-Stage Material Traceability with SHA-256',
    acceptPickup: 'Accept Pickup',
    citizenName: 'Citizen',
    estimatedPayout: 'Estimated Payout',
    itemsDeclared: 'Declared Scrap Items',

    // New smart localization keys
    verifiedCollector: 'VERIFIED COLLECTOR',
    verifiedCitizen: 'VERIFIED CITIZEN',
    verifiedRecycler: 'AUTHORIZED RECYCLER',
    verifiedAdmin: 'REGULATORY AUTHORITY',
    cashFirst: 'Cash-First Support',
    offlineMode: 'Offline Mode',
    onlineMode: 'Online',
    offlineModeActive: 'Offline Mode Active:',
    offlineModeDesc: 'Lots are cached locally in your phone storage and queued for auto-sync.',
    syncPendingLots: 'Sync Pending Lots',
    operatingZone: 'Operating Zone: Pan-India Active Network',
    yourPickupRequests: 'Your Pickup Requests',
    verifiedHandover: 'Verified Handover',
    callCollector: 'Call Collector',
    bookPickupHeader: 'Book Doorstep E-Waste Pickup',
    householdPickupBadge: 'Doorstep Pickup',
    aiPhotoScanner: 'AI Photo Scanner (Upload Photo for Auto-Classification)',
    priceRangeTitle: 'Indicative Market Price Range',
    donateToCsrLabel: 'Donate Scrap Value to Environmental NGO (Plant Trees)',
    confirmPickupBtn: 'Confirm & Request Doorstep Pickup',
    traceabilityGuarantee: 'Dhatu Traceability & Chain of Custody Guarantee',
    traceabilityBadge: 'Verified Chain',
    environmentalImpactHeader: 'Environmental Impact & Diversion Ledger',
    personalImpactTitle: 'Your Environmental & Landfill Diversion Impact',
    downloadCertBtn: 'Download Disposal Certificate',
    ewasteDiverted: 'E-Waste Diverted from Landfills',
    carbonSaved: 'Carbon Emissions Avoided',
    metalsRecycled: 'Precious Metals & Copper Recycled',
    csrCreditsEarned: 'CSR Green Credits Earned',
    selfDropoffTitle: 'Authorized E-Waste Drop-Off Centers',
    selfDropoffBadge: 'Self Drop-Off Option',
    verifiedReceiptModalTitle: 'Verified Digital Handover Receipt',
    mandiPriceBoardTitle: 'Live Material Benchmark Price Board',
    digitalLotCreatorTitle: 'Digital E-Waste Lot Creator',
    lotCreationBadge: 'Lot Creation',
    lotCreatedSuccessTitle: 'Lot Registered Successfully!',
    uploadPhotoLabel: '1. Upload or Capture Photograph',
    tapToSnapPhoto: 'Open Camera or Snap Photo',
    photoCapturedMsg: 'Photo Captured & Verified (1080p)',
    approxWeightLabel: '3. Enter Approx Weight (Kilograms)',
    minWeightNote: 'Minimum 0.5 kg',
    sellLotHere: 'Sell Lot to this Facility',
    nearbyRecyclersTitle: 'Authorized Recyclers & Smelters',
    handoverVoucherTitle: 'Digital Handover QR Voucher',
    handoverVoucherBadge: 'Digital Handover',
    handoverStepsTitle: '3 Easy Steps for Handover',
    step1Weight: 'Weight Check at Recycler Gate',
    step1Desc: 'Weigh items on calibrated electronic scale.',
    step2Scan: 'Scan Handover QR Code',
    step2Desc: 'Recycler operator scans voucher with their phone.',
    step3Pay: 'Receive Cash or Wallet Payout',
    step3Desc: 'Receive immediate cash or wallet escrow payment. Recorded in passbook.',
    formalizationBenefitTitle: 'Ministry of Mines Formalization Incentive:',
    formalizationBenefitDesc: 'Earn ₹500 formalization loyalty bonus for every verified digital lot handover.',
    passbookTitle: 'Collector Running Passbook Ledger',
    passbookBadge: 'Cash Passbook',
    thDate: 'Date',
    thDesc: 'Description',
    thParty: 'Party',
    thMode: 'Mode',
    thAmount: 'Amount',
    thBalance: 'Balance',
    thStamp: 'Stamp',
    cashPaymentRule: 'Cash Payment Rule: All cash handovers are automatically stamped and logged into the running passbook.',
    downloadPassbookPdf: 'Download Passbook PDF',
    safetyCardsTitle: 'Safety Rules & Hazardous Practice Prevention',
    safetyBadge: 'Safety Guidance',
    cpcbSafetyGuidelines: 'CPCB Mandatory E-Waste Safety Guidelines',
    dosTitle: "DO'S:",
    dontsTitle: "DON'TS:",
    safetyQuote: 'Proper segregation protects worker health and yields up to 35% higher buyback value from formal smelters.',
    valuePreservationTitle: '4 Rules of Value-Preservation Disassembly for Maximum Earnings',
    valueBadge: 'Value Maximization Guide',
    step1Plastic: 'Step 1: Unscrew External Plastic',
    step1PlasticDesc: 'Remove clean ABS plastic housing without smashing screws (sells separately at ₹38/kg).',
    step2Pcb: 'Step 2: Keep Circuit Boards Whole',
    step2PcbDesc: 'High-grade motherboards sell at ₹640/kg when components and gold pins remain intact.',
    step3Copper: 'Step 3: Strip Copper Cold',
    step3CopperDesc: 'Extract copper windings using hand wire-strippers without open-flame burning (₹480/kg).',
    step4Battery: 'Step 4: Bag Batteries Separately',
    step4BatteryDesc: 'Keep lithium cells insulated in a dry bag to prevent punctures, sparks, or thermal runaways.',
    citizenPickupRequestsTitle: 'Nearby Citizen Pickup Requests',
    citizenPickupsBadge: 'Citizen Pickups',
    refreshBtn: 'Refresh',
    jobCompletedTitle: 'Job Completed!',
    activeJobBadge: 'IN PROGRESS',
    callBtn: 'Call',
    verifyWeightTitle: 'Verify & Adjust Final Weight:',
    completePickupBtn: 'Complete Pickup & Issue Digital Receipt',
    livePickupsMapTitle: 'Live e-Waste Pickups Map',
    simulationControls: 'Simulation Controls',
    unitEconomicsBadge: 'Unit-Economics Calculator',
    platformSustainability: 'Platform Sustainability Model:',
    informalMarketLabel: 'Informal Scrap Market (Status Quo)',
    formalPlatformLabel: 'Kabadiwala Connect Platform (Formalized)',
    collectorKycTitle: 'Collector KYC Verification & Identity Cards',
    collectorKycBadge: 'KYC Verification',
    kycVerified: 'VERIFIED',
    kycPending: 'VERIFICATION PENDING'
  },
  hi: {
    appName: 'कबाड़ीवाला कनेक्ट',
    tagline: 'ई-कचरा ट्रेसेबिलिटी एवं ईपीआर एक्सचेंज',
    dhatuTag: 'धातु — ई-कचरा ट्रेसेबिलिटी एवं औपचारिकीकरण मंच',
    dhatuSub: 'धातु — अनौपचारिक स्क्रैप एवं अधिकृत रीसायकलर मंच',
    sihBadge: 'SIH26229',
    sihSub: 'खान मंत्रालय — अनौपचारिक ई-कचरा एकीकरण पहल',
    activeTerminal: 'सक्रिय टर्मिनल',
    switchRole: 'भूमिका पोर्टल बदलें',
    signIn: 'पोर्टल में प्रवेश',
    signInBtn: 'पोर्टल में लॉगिन करें',
    signOut: 'लॉगआउट करें',
    langSelect: 'भाषा बदलें',
    selectLanguage: 'भाषा चयन',
    listen: 'बोलकर सुनें',
    stop: 'आवाज़ रोकें',
    initializing: 'प्रारंभ हो रहा है...',

    portalCitizen: 'नागरिक पोर्टल',
    portalCollector: 'कबाड़ीवाला पोर्टल',
    portalRecycler: 'पुनर्चक्रणकर्ता (रीसायकलर)',
    portalAdmin: 'प्रशासन / सीपीसीबी ऑडिट',
    roleCitizen: 'नागरिक एवं घरेलू उपभोक्ता',
    roleCollector: 'कबाड़ीवाला (संग्राहक)',
    roleRecycler: 'अधिकृत रीसायकलर / एग्रीगेटर',
    roleAdmin: 'प्रशासन एवं सीपीसीबी ऑडिट',
    personaCitizen: 'रमेश शर्मा',
    personaCollector: 'सुरेश कुमार',
    personaRecycler: 'इको-रीसायकल एग्रीगेटर्स लिमिटेड',
    personaAdmin: 'एनडीएमसी अपशिष्ट एवं खान प्रकोष्ठ',

    heroTitle: "धातु — भारत की ई-कचरा अर्थव्यवस्था हेतु डिजिटल ट्रेसेबिलिटी एवं ईपीआर मंच",
    heroSubtitle: "घर-घर जाने वाले कबाड़ीवालों को अधिकृत सीपीसीबी रीसायकलर्स से जोड़ना। कम साक्षरता, बिना इंटरनेट सुविधा और बहुभाषी नकद पासबुक पर आधारित डिजिटल प्रणाली।",
    roleBasedLogin: 'रोल अनुसार पोर्टल लॉगिन',
    sourcingLayer: 'सोर्सिंग स्तर (रमेश)',
    coreAsk: 'मुख्य उद्देश्य (SIH26229)',
    formalSide: 'औपचारिक रिसाइकलिंग स्तर',
    regulatoryLayer: 'विनियामक डेटा स्तर',
    citizenCardDesc: 'घर बैठे ई-कचरा पिकअप बुक करें, तुरंत अनुमानित मूल्य देखें, कबाड़ीवाले की लाइव लोकेशन ट्रैक करें और ग्रीन ट्री क्रेडिट पाएं।',
    collectorCardDesc: 'बोलता दाम पत्रक, सरल लॉट निर्माण, क्यूआर कोड रसीद, नकद खाता बही (पासबुक) और सुरक्षा कार्ड।',
    recyclerCardDesc: 'आने वाले लॉट की जांच (स्वीकार/अस्वीकार), क्यूआर स्कैन, लाइव दाम प्रसारण और सीपीसीबी फॉर्म-२ एवं फॉर्म-६ रिपोर्ट।',
    adminCardDesc: 'शहर भर के आंकड़े, एसएचए-२५६ हैश सहित ४-चरणीय ट्रेसेबिलिटी और कबाड़ीवाला आधार केवाईसी सत्यापन।',
    enterAsCitizen: 'नागरिक के रूप में प्रवेश करें',
    enterAsCollector: 'कबाड़ीवाले के रूप में प्रवेश करें',
    enterAsRecycler: 'रीसायकलर के रूप में प्रवेश करें',
    enterAsAdmin: 'प्रशासन के रूप में प्रवेश करें',

    authGateway: 'भूमिका आधारित प्रमाणीकरण गेटवे',
    selectRole: 'अपनी भूमिका का चयन करें',
    loginSubtitle: 'कबाड़ीवाला कनेक्ट भारत की औपचारिक ई-कचरा रीसाइक्लिंग प्रणाली के प्रत्येक हितधारक हेतु समर्पित पोर्टल प्रदान करता है।',
    instantLogin: 'एक क्लिक में त्वरित लॉगिन -',
    orCredentials: 'या अपना विवरण दर्ज करें',
    mobileNumber: 'पंजीकृत मोबाइल नंबर',
    cpcbRegNumber: 'सीपीसीबी संयंत्र पंजीकरण संख्या / मोबाइल',
    password: 'सुरक्षा पासवर्ड या ४-अंकों का पिन',
    submitLogin: 'जमा करें एवं डैशबोर्ड खोलें',
    dedicatedFeatures: 'इस पोर्टल की प्रमुख समर्पित सुविधाएं',
    activeTabBadge: 'सक्रिय',

    status: 'स्थिति',
    actions: 'कार्यवाही',
    submit: 'जमा करें',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    back: 'वापस जाएं',
    delete: 'हटाएं',
    loading: 'लोड हो रहा है...',
    verified: 'सत्यापित',
    pending: 'लंबित',
    completed: 'संपन्न हुआ',
    assigned: 'कबाड़ीवाला आवंटित',
    inProgress: 'प्रगति पर है',
    requested: 'अनुरोध प्राप्त',
    accepted: 'स्वीकृत',
    rejected: 'अस्वीकृत',
    viewDetails: 'विवरण देखें',
    close: 'बंद करें',
    date: 'दिनांक',
    weight: 'वजन',
    amount: 'राशि',
    total: 'कुल योग',
    ratePerKg: 'दर प्रति किग्रा',
    perKg: 'प्रति किग्रा',
    estValue: 'अनुमानित मूल्य',
    mandiRate: 'मंडी बेंचमार्क दर',
    itemMaterial: 'वस्तु / सामग्री',

    tabMyPickups: 'मेरे पिकअप',
    tabSchedulePickup: 'पिकअप बुक करें',
    tabImpact: 'लैंडफिल प्रभाव एवं वृक्ष',
    tabDropoff: 'निकटतम ड्रॉप-ऑफ केंद्र',
    pickupAddress: 'पिकअप का पता',
    scheduledTime: 'निर्धारित दिनांक एवं समय',
    notesCarton: 'सामग्री विवरण / नोट',
    itemsToRecycle: 'ई-कचरा सामग्री',
    addMoreItems: 'अन्य वस्तु जोड़ें',
    scanAiPhoto: 'एआई कैमरे से स्क्रैप स्कैन करें',
    indicativePriceRange: 'अनुमानित मूल्य दायरा',
    confirmPickup: 'पुष्टि करें एवं पिकअप मंगाएं',
    collectorTracking: 'कबाड़ीवाला आ रहा है',
    collectorEta: 'अनुमानित आगमन: १२ मिनट',
    viewReceipt: 'सत्यापित रसीद देखें',
    downloadCert: 'सुरक्षित निपटान प्रमाणपत्र डाउनलोड करें',
    csrDonationNote: 'वृक्षारोपण हेतु यह राशि ग्रीन अर्थ एनजीओ को दान करें',
    treesPlanted: 'लगाए गए वृक्ष',
    landfillDivertedKg: 'किग्रा कचरा लैंडफिल से बचाया',
    dropoffTitle: 'अधिकृत ई-कचरा ड्रॉप-ऑफ केंद्र',

    tabLots: 'मेरे लॉट',
    tabPriceBoard: 'बोलता दाम पत्रक',
    tabFindRecyclers: 'निकटतम रीसायकलर',
    tabHandover: 'क्यूआर बनाएं',
    tabPassbook: 'नकद पासबुक',
    tabSafety: 'सुरक्षा नियम',
    createLot: 'नया लॉट बनाएं',
    selectScrapCategory: 'वस्तु श्रेणी चुनें',
    lotWeightKg: 'लॉट का वजन (किग्रा)',
    takePhotoProof: 'कबाड़ का फोटो लें',
    saveLot: 'खाते में लॉट दर्ज करें',
    listenPriceAloud: 'दाम बोलकर सुनें',
    todayMandiRate: 'आज का मंडी बेंचमार्क भाव',
    passbookBalance: 'खातावही शेष',
    cashCollected: 'कुल प्राप्त नकद',
    totalSoldLots: 'कुल बेचे गए लॉट',
    runningLedger: 'नकद एवं लॉट लेनदेन खाता बही',
    credit: 'जमा (+)',
    debit: 'निकासी (-)',
    balance: 'शेष',
    offlineTolerant: 'ऑफलाइन मोड सक्रिय (इंटरनेट की आवश्यकता नहीं)',
    syncPending: 'लंबित लॉट',
    syncNow: 'अभी सिंक करें',
    safetyRulesTitle: 'सचित्र एवं बोलती सुरक्षा मार्गदर्शिका',

    tabIncoming: 'आने वाले लॉट',
    tabVerifyQr: 'हस्तांतरण क्यूआर जांचें',
    tabRateConsole: 'खरीद दर नियंत्रण',
    tabAnomalies: 'एआई विसंगति जांच',
    tabReports: 'सीपीसीबी ईपीआर रिपोर्ट',
    tabFacility: 'संयंत्र विवरण',
    lotCode: 'लॉट कोड',
    collectorName: 'कबाड़ीवाला',
    approxWeight: 'अनुमानित वजन (किग्रा)',
    offeredRate: 'प्रस्तावित दर (₹/किग्रा)',
    totalAmount: 'कुल देय राशि',
    acceptLot: 'लॉट स्वीकार करें',
    rejectLot: 'अस्वीकार करें',
    counterOffer: 'वैकल्पिक दर दें',
    broadcastRates: 'सभी कबाड़ीवालों को नई दरें भेजें',
    downloadForm2: 'सीपीसीबी फॉर्म-२ (JSON) डाउनलोड करें',
    downloadForm6: 'सीपीसीबी फॉर्म-६ (CSV) डाउनलोड करें',
    facilityRegStatus: 'सीपीसीबी ईपीआर पंजीकरण सक्रिय',

    tabOverview: 'शहर स्तरीय अवलोकन',
    tabTraceability: 'सामग्री ट्रेसेबिलिटी श्रृंखला',
    tabUnitEconomics: 'इकाई-अर्थशास्त्र कैलकुलेटर',
    tabVerifications: 'कबाड़ीवाला केवाईसी सत्यापन',
    tabEpr: 'सीपीसीबी २०२२ डेटा निर्यात',
    citywideTonnage: 'कुल एकत्र ई-कचरा',
    activeCollectors: 'पंजीकृत औपचारिक कबाड़ीवाले',
    authorizedSmelters: 'सीपीसीबी अधिकृत रीसाइक्लिंग संयंत्र',
    monthlyVolume: 'मासिक संग्रह (किग्रा)',
    middlemanCut: 'समाप्त की गई बिचौलियों की दलाली',
    incomeBoost: 'कबाड़ीवाले की शुद्ध आय में वृद्धि',
    approveKyc: 'स्वीकृत करें एवं सीपीसीबी बैज जारी करें',
    rejectKyc: 'अस्वीकार करें',
    traceabilityTitle: 'एसएचए-२५६ सहित ४-चरणीय सामग्री ट्रेसेबिलिटी',
    acceptPickup: 'पिकअप स्वीकार करें',
    citizenName: 'नागरिक',
    estimatedPayout: 'अनुमानित भुगतान',
    itemsDeclared: 'घोषित कबाड़ सामग्री',

    // New smart localization keys
    verifiedCollector: 'सत्यापित कबाड़ीवाला',
    verifiedCitizen: 'सत्यापित नागरिक',
    verifiedRecycler: 'अधिकृत रीसायकलर',
    verifiedAdmin: 'नियामक प्राधिकरण',
    cashFirst: 'नकद समर्थित',
    offlineMode: 'ऑफलाइन मोड',
    onlineMode: 'ऑनलाइन',
    offlineModeActive: 'ऑफलाइन मोड सक्रिय:',
    offlineModeDesc: 'लॉट आपके फोन स्टोरेज में सुरक्षित हैं और नेटवर्क आने पर अपने आप सिंक हो जाएंगे।',
    syncPendingLots: 'लंबित लॉट सिंक करें',
    operatingZone: 'कार्य क्षेत्र: अखिल भारतीय सक्रिय नेटवर्क',
    yourPickupRequests: 'आपके पिकअप अनुरोध',
    verifiedHandover: 'सत्यापित हस्तांतरण',
    callCollector: 'कबाड़ीवाले को कॉल करें',
    bookPickupHeader: 'घरेलू ई-कचरा पिकअप बुक करें',
    householdPickupBadge: 'घरेलू पिकअप',
    aiPhotoScanner: 'एआई फोटो स्कैनर (स्वचालित श्रेणी पहचान)',
    priceRangeTitle: 'अनुमानित बाजार मूल्य दायरा',
    donateToCsrLabel: 'पर्यावरण एनजीओ को राशि दान करें (पौधे लगाएं)',
    confirmPickupBtn: 'पुष्टि करें एवं घर पर पिकअप मंगाएं',
    traceabilityGuarantee: 'धातु ट्रेसेबिलिटी एवं शुद्धता गारंटी',
    traceabilityBadge: 'सत्यापित श्रृंखला',
    environmentalImpactHeader: 'पर्यावरण प्रभाव एवं लैंडफिल डायवर्जन बही',
    personalImpactTitle: 'आपका व्यक्तिगत लैंडफिल डायवर्जन प्रभाव',
    downloadCertBtn: 'निपटान प्रमाणपत्र डाउनलोड करें',
    ewasteDiverted: 'ई-कचरा लैंडफिल से बचाया',
    carbonSaved: 'कार्बन डाइऑक्साइड उत्सर्जन बचत',
    metalsRecycled: 'मूल्यवान धातु एवं तांबा पुनर्चक्रण',
    csrCreditsEarned: 'सीएसआर ग्रीन क्रेडिट अर्जित',
    selfDropoffTitle: 'अधिकृत ई-कचरा ड्रॉप-ऑफ केंद्र',
    selfDropoffBadge: 'स्वयं ड्रॉप-ऑफ विकल्प',
    verifiedReceiptModalTitle: 'सत्यापित डिजिटल हस्तांतरण रसीद',
    mandiPriceBoardTitle: 'लाइव ई-कचरा मंडी बेंचमार्क भाव',
    digitalLotCreatorTitle: 'ई-कचरा डिजिटल लॉट बनाएं',
    lotCreationBadge: 'लॉट निर्माण',
    lotCreatedSuccessTitle: 'लॉट सफलतापूर्वक दर्ज!',
    uploadPhotoLabel: '१. कबाड़ की फोटो लें या अपलोड करें',
    tapToSnapPhoto: 'कैमरा खोलें या फोटो खींचें',
    photoCapturedMsg: 'फोटो कैप्चर एवं सत्यापित (1080p)',
    approxWeightLabel: '३. अनुमानित वजन दर्ज करें (किग्रा)',
    minWeightNote: 'न्यूनतम ०.५ किग्रा',
    sellLotHere: 'इस संयंत्र को लॉट बेचें',
    nearbyRecyclersTitle: 'पास के अधिकृत रीसायकलर एवं स्मेल्टर',
    handoverVoucherTitle: 'डिजिटल हस्तांतरण क्यूआर वाउचर',
    handoverVoucherBadge: 'डिजिटल हस्तांतरण',
    handoverStepsTitle: 'हस्तांतरण प्रक्रिया के ३ आसान कदम',
    step1Weight: 'रीसायकलर गेट पर वजन कराएं',
    step1Desc: 'धर्मकांटे या प्रमाणित इलेक्ट्रॉनिक कांटे पर वजन दर्ज कराएं।',
    step2Scan: 'हस्तांतरण क्यूआर स्कैन कराएं',
    step2Desc: 'रीसायकलर ऑपरेटर अपने फोन से यह वाउचर स्कैन करेगा।',
    step3Pay: 'नकद या वॉलेट भुगतान प्राप्त करें',
    step3Desc: 'तुरंत नकद लें या डिजिटल एस्क्रो में भुगतान पाएं। पासबुक में दर्ज।',
    formalizationBenefitTitle: 'खान मंत्रालय औपचारिकीकरण प्रोत्साहन:',
    formalizationBenefitDesc: 'प्रत्येक सत्यापित डिजिटल लॉट हस्तांतरण पर ₹५०० विशेष औपचारिकीकरण बोनस।',
    passbookTitle: 'कबाड़ीवाला नकद खाता बही (पासबुक)',
    passbookBadge: 'नकद पासबुक',
    thDate: 'दिनांक',
    thDesc: 'विवरण',
    thParty: 'पक्षकार',
    thMode: 'माध्यम',
    thAmount: 'राशि',
    thBalance: 'शेष',
    thStamp: 'मुहर',
    cashPaymentRule: 'नकद भुगतान नियम: सभी नकद लेनदेन डिजिटल रूप से मुहरबंद होकर पासबुक में दर्ज होते हैं।',
    downloadPassbookPdf: 'पासबुक पीडीएफ डाउनलोड करें',
    safetyCardsTitle: 'सुरक्षा नियम एवं खतरनाक प्रथाओं से बचाव',
    safetyBadge: 'सुरक्षा मार्गदर्शन',
    cpcbSafetyGuidelines: 'सीपीसीबी अनिवार्य ई-कचरा सुरक्षा दिशा-निर्देश',
    dosTitle: "क्या करें (DO'S):",
    dontsTitle: "कभी न करें (DON'TS):",
    safetyQuote: 'उचित पृथक्करण से स्वास्थ्य की रक्षा होती है और रीसायकलर ३५% अधिक मूल्य देता है।',
    valuePreservationTitle: 'सर्वाधिक कमाई के लिए सुरक्षित डिसमेंटलिंग के ४ नियम',
    valueBadge: 'मूल्य संवर्धन मार्गदर्शिका',
    step1Plastic: 'कदम १: बाहरी प्लास्टिक खोलें',
    step1PlasticDesc: 'बिना तोड़े स्क्रू खोलकर एबीएस प्लास्टिक केसिंग अलग करें (₹३८/किग्रा अलग बिकेगी)।',
    step2Pcb: 'कदम २: मदरबोर्ड साबुत रखें',
    step2PcbDesc: 'हाई-ग्रेड मदरबोर्ड के पुर्जे और सोने की पिने सुरक्षित रखने पर ₹६४०/किग्रा मिलता है।',
    step3Copper: 'कदम ३: कॉपर वाइंडिंग ठंडा छीलें',
    step3CopperDesc: 'मोटर का तांबा बिना जलाए वायर कटर से निकालें (₹४८०/किग्रा)।',
    step4Battery: 'कदम ४: बैटरियों को अलग थैले में रखें',
    step4BatteryDesc: 'शॉर्ट सर्किट और आग से बचाव के लिए लिथियम सेलों को अलग सूखे बैग में रखें।',
    citizenPickupRequestsTitle: 'पास के घरों से पिकअप अनुरोध',
    citizenPickupsBadge: 'नागरिक पिकअप',
    refreshBtn: 'ताज़ा करें',
    jobCompletedTitle: 'कार्य सफलतापूर्वक पूर्ण!',
    activeJobBadge: 'सक्रिय कार्य',
    callBtn: 'कॉल करें',
    verifyWeightTitle: 'अंतिम वजन सत्यापन एवं समायोजन:',
    completePickupBtn: 'पिकअप पूरा करें एवं रसीद जारी करें',
    livePickupsMapTitle: 'लाइव कबाड़ पिकअप मैप',
    simulationControls: 'सिमुलेशन नियंत्रण',
    unitEconomicsBadge: 'इकाई अर्थशास्त्र कैलकुलेटर',
    platformSustainability: 'मंच आत्मनिर्भरता मॉडल:',
    informalMarketLabel: 'वर्तमान अनौपचारिक बाजार (यथास्थिति)',
    formalPlatformLabel: 'कबाड़ीवाला कनेक्ट मंच (औपचारिक)',
    collectorKycTitle: 'कबाड़ीवाला सत्यापन एवं पहचान पत्र',
    collectorKycBadge: 'केवाईसी सत्यापन',
    kycVerified: 'सत्यापित',
    kycPending: 'सत्यापन लंबित'
  },
  mr: {
    appName: 'कबाडीवाला कनेक्ट',
    tagline: 'ई-कचरा ट्रेसेबिलिटी आणि ईपीआर एक्सचेंज',
    dhatuTag: 'धातु — ई-कचरा मागोवा आणि औपचारिकीकरण व्यासपीठ',
    dhatuSub: 'धातु — अनौपचारिक स्क्रॅप आणि अधिकृत रीसायकलिंग व्यासपीठ',
    sihBadge: 'SIH26229',
    sihSub: 'खाण मंत्रालय — अनौपचारिक ई-कचरा एकत्रीकरण उपक्रम',
    activeTerminal: 'सक्रिय टर्मिनल',
    switchRole: 'भूमिका डॅशबोर्ड बदला',
    signIn: 'प्रवेश करा',
    signInBtn: 'डॅशबोर्डमध्ये लॉगिन करा',
    signOut: 'लॉगआउट करा',
    langSelect: 'भाषा बदला',
    selectLanguage: 'भाषा निवडा',
    listen: 'ऐका',
    stop: 'आवाज थांबवा',
    initializing: 'प्रारंभ होत आहे...',

    portalCitizen: 'नागरिक पोर्टल',
    portalCollector: 'भंगार संग्राहक पोर्टल',
    portalRecycler: 'अधिकृत रीसायकलर',
    portalAdmin: 'प्रशासन / सीपीसीबी तपासणी',
    roleCitizen: 'नागरिक व घरगुती ग्राहक',
    roleCollector: 'भंगार संग्राहक',
    roleRecycler: 'अधिकृत रीसायकलर',
    roleAdmin: 'प्रशासन व सीपीसीबी तपासणी',
    personaCitizen: 'रमेश शर्मा',
    personaCollector: 'सुरेश कुमार',
    personaRecycler: 'इको-रीसायकल अ‍ॅग्रीगेटर्स लि.',
    personaAdmin: 'एनडीएमसी कचरा आणि खाण विभाग',

    heroTitle: "धातु — भारताच्या ई-कचरा अर्थव्यवस्थेसाठी डिजिटल मागोवा व ईपीआर व्यासपीठ",
    heroSubtitle: "घरोघरी भंगार गोळा करणाऱ्यांना थेट अधिकृत सीपीसीबी रीसायकलरशी जोडणे. कमी साक्षरता, विनाइंटरनेट सुविधा आणि बहुभाषिक रोख पासबुकवर आधारित डिजिटल प्रणाली.",
    roleBasedLogin: 'भूमिका आधारित लॉगिन',
    sourcingLayer: 'संकलन स्तर (रमेश)',
    coreAsk: 'प्रमुख उद्दिष्ट (SIH26229)',
    formalSide: 'औपचारिक रीसायकलिंग स्तर',
    regulatoryLayer: 'नियामक डेटा स्तर',
    citizenCardDesc: 'घरी बसून जुन्या इलेक्ट्रॉनिक्ससाठी पिकअप बुक करा, थेट अंदाज दर पहा, संग्राहकाचे थेट लोकेशन तपासा आणि ग्रीन ट्री क्रेडिट मिळवा.',
    collectorCardDesc: 'बोलणारा भाव फलक, सोपी लॉट नोंदणी, क्यूआर पावती, रोख पासबुक आणि सुरक्षा नियम.',
    recyclerCardDesc: 'येणाऱ्या लॉटची तपासणी (स्वीकार/नकार), क्यूआर स्कॅन, थेट दर प्रसारण आणि सीपीसीबी फॉर्म-२ व फॉर्म-६ अहवाल.',
    adminCardDesc: 'शहरपातळीवरील आकडेवारी, एसएचए-२५६ सह ४-टप्प्यातील सामग्री मागोवा आणि केवायसी पडताळणी.',
    enterAsCitizen: 'नागरिक म्हणून प्रवेश करा',
    enterAsCollector: 'संग्राहक म्हणून प्रवेश करा',
    enterAsRecycler: 'रीसायकलर म्हणून प्रवेश करा',
    enterAsAdmin: 'प्रशासन म्हणून प्रवेश करा',

    authGateway: 'भूमिका आधारित प्रमाणीकरण गेटवे',
    selectRole: 'आपली भूमिका निवडा',
    loginSubtitle: 'कबाडीवाला कनेक्ट भारताच्या ई-कचरा पुनर्प्रक्रिया साखळीतील प्रत्येक घटकासाठी स्वतंत्र डॅशबोर्ड उपलब्ध करून देतो.',
    instantLogin: 'एका क्लिकवर त्वरित लॉगिन -',
    orCredentials: 'किंवा आपली माहिती प्रविष्ट करा',
    mobileNumber: 'नोंदणीकृत मोबाइल क्रमांक',
    cpcbRegNumber: 'सीपीसीबी प्रकल्प नोंदणी क्रमांक / मोबाइल',
    password: 'सुरक्षा पासवर्ड किंवा ४-अंकी पिन',
    submitLogin: 'सबमिट करा आणि डॅशबोर्ड उघडा',
    dedicatedFeatures: 'या पोर्टलची प्रमुख वैशिष्ट्ये',
    activeTabBadge: 'सक्रिय',

    status: 'स्थिती',
    actions: 'कृती',
    submit: 'सबमिट करा',
    cancel: 'रद्द करा',
    save: 'जतन करा',
    back: 'मागे जा',
    delete: 'हटवा',
    loading: 'लोड होत आहे...',
    verified: 'प्रमाणित',
    pending: 'प्रलंबित',
    completed: 'पूर्ण झाले',
    assigned: 'संग्राहक नेमला',
    inProgress: 'सुरू आहे',
    requested: 'विनंती प्राप्त',
    accepted: 'स्वीकारले',
    rejected: 'नाकारले',
    viewDetails: 'तपशील पहा',
    close: 'बंद करा',
    date: 'दिनांक',
    weight: 'वजन',
    amount: 'रक्कम',
    total: 'एकूण बेरीज',
    ratePerKg: 'दर प्रति किलो',
    perKg: 'प्रति किलो',
    estValue: 'अंदाजे किंमत',
    mandiRate: 'बाजार भाव दर',
    itemMaterial: 'वस्तू / सामग्री',

    tabMyPickups: 'माझ्या संकलन विनंत्या',
    tabSchedulePickup: 'संकलन बुक करा',
    tabImpact: 'पर्यावरण प्रभाव व वृक्ष',
    tabDropoff: 'जवळची केंद्रे',
    pickupAddress: 'संकलनाचा पत्ता',
    scheduledTime: 'नियोजित दिनांक व वेळ',
    notesCarton: 'वस्तूंचे वर्णन / टीप',
    itemsToRecycle: 'ई-कचरा वस्तू',
    addMoreItems: 'आणखी वस्तू जोडा',
    scanAiPhoto: 'एआय कॅमेऱ्याने स्कॅन करा',
    indicativePriceRange: 'अंदाजे किंमत श्रेणी',
    confirmPickup: 'खात्री करा व विनंती पाठवा',
    collectorTracking: 'संग्राहक येत आहे',
    collectorEta: 'अंदाजे आगमन: १२ मिनिटांत',
    viewReceipt: 'प्रमाणित डिजिटल पावती पहा',
    downloadCert: 'सुरक्षित विल्हेवाट प्रमाणपत्र डाउनलोड करा',
    csrDonationNote: 'वृक्षारोपणासाठी ही रक्कम ग्रीन अर्थ एनजीओला दान करा',
    treesPlanted: 'लावलेली झाडे',
    landfillDivertedKg: 'कि.ग्रा. ई-कचरा डेपोत जाण्यापासून वाचवला',
    dropoffTitle: 'सीपीसीबी अधिकृत ई-कचरा संकलन केंद्रे',

    tabLots: 'माझे लॉट',
    tabPriceBoard: 'बोलणारा भाव फलक',
    tabFindRecyclers: 'जवळचे रीसायकलर',
    tabHandover: 'क्यूआर तयार करा',
    tabPassbook: 'रोख पासबुक',
    tabSafety: 'सुरक्षा नियम',
    createLot: 'नवीन लॉट तयार करा',
    selectScrapCategory: 'वस्तू प्रकार निवडा',
    lotWeightKg: 'लॉटचे वजन (कि.ग्रा.)',
    takePhotoProof: 'भंगाराचा फोटो घ्या',
    saveLot: 'खात्यात लॉट नोंदवा',
    listenPriceAloud: 'भाव ऐका',
    todayMandiRate: 'आजचा बाजार भाव दर',
    passbookBalance: 'पासबुक शिल्लक',
    cashCollected: 'एकूण मिळालेली रोख',
    totalSoldLots: 'एकूण विकलेले लॉट',
    runningLedger: 'रोख व लॉट व्यवहार नोंदवही',
    credit: 'जमा (+)',
    debit: 'नावे (-)',
    balance: 'शिल्लक',
    offlineTolerant: 'ऑफलाइन मोड सक्रिय (इंटरनेट नसतानाही लॉट जतन करा)',
    syncPending: 'सिंक बाकी असलेले लॉट',
    syncNow: 'आता सिंक करा',
    safetyRulesTitle: 'चित्रांसह बोलणारे सुरक्षा नियम',

    tabIncoming: 'येणारे लॉट',
    tabVerifyQr: 'हस्तांतरण क्यूआर तपासा',
    tabRateConsole: 'खरेदी दर नियंत्रण',
    tabAnomalies: 'एआय त्रुटी तपासणी',
    tabReports: 'सीपीसीबी ईपीआर अहवाल',
    tabFacility: 'प्रकल्प माहिती',
    lotCode: 'लॉट कोड',
    collectorName: 'भंगार संग्राहक',
    approxWeight: 'अंदाजे वजन (कि.ग्रा.)',
    offeredRate: 'दिलेला दर (₹/कि.ग्रा.)',
    totalAmount: 'एकूण देय रक्कम',
    acceptLot: 'लॉट स्वीकारा',
    rejectLot: 'नाकारा',
    counterOffer: 'पर्यायी दर द्या',
    broadcastRates: 'सर्व कबाडीवाल्यांना नवे दर पाठवा',
    downloadForm2: 'सीपीसीबी फॉर्म-२ (JSON) डाउनलोड करा',
    downloadForm6: 'सीपीसीबी फॉर्म-६ (CSV) डाउनलोड करा',
    facilityRegStatus: 'सीपीसीबी ईपीआर नोंदणी सक्रिय',

    tabOverview: 'शहरस्तरीय आढावा',
    tabTraceability: 'साहित्य मागोवा साखळी',
    tabUnitEconomics: 'आर्थिक नफा कॅल्क्युलेटर',
    tabVerifications: 'कबाडीवाला केवायसी पडताळणी',
    tabEpr: 'सीपीसीबी २०२२ डेटा निर्यात',
    citywideTonnage: 'एकूण गोळा केलेला ई-कचरा',
    activeCollectors: 'नोंदणीकृत भंगार संग्राहक',
    authorizedSmelters: 'सीपीसीबी अधिकृत रीसायकलिंग प्रकल्प',
    monthlyVolume: 'मासिक संकलन (कि.ग्रा.)',
    middlemanCut: 'कमी केलेले मध्यस्थांचे कमिशन',
    incomeBoost: 'संग्राहकाच्या उत्पन्नातील निव्वळ वाढ',
    approveKyc: 'मंजूर करा व सीपीसीबी बॅज द्या',
    rejectKyc: 'नाकारा',
    traceabilityTitle: 'एसएचए-२५६ सह ४-टप्प्यातील सामग्री मागोवा',
    acceptPickup: 'पिकअप स्वीकारा',
    citizenName: 'नागरिक',
    estimatedPayout: 'अंदाजे रक्कम',
    itemsDeclared: 'नोंदणी केलेले साहित्य',

    // New smart localization keys
    verifiedCollector: 'सत्यापित संग्राहक',
    verifiedCitizen: 'सत्यापित नागरिक',
    verifiedRecycler: 'अधिकृत रीसायकलर',
    verifiedAdmin: 'नियामक प्राधिकरण',
    cashFirst: 'रोख प्राधान्य',
    offlineMode: 'ऑफलाइन मोड',
    onlineMode: 'ऑनलाइन',
    offlineModeActive: 'ऑफलाइन मोड सक्रिय:',
    offlineModeDesc: 'लॉट तुमच्या फोन स्टोरेजमध्ये सुरक्षित आहेत आणि नेटवर्क आल्यावर सिंक होतील.',
    syncPendingLots: 'प्रलंबित लॉट सिंक करा',
    operatingZone: 'कार्यक्षेत्र: पॅन-इंडिया सक्रिय नेटवर्क',
    yourPickupRequests: 'आपल्या संकलन विनंत्या',
    verifiedHandover: 'प्रमाणित हस्तांतरण',
    callCollector: 'संग्राहकाला कॉल करा',
    bookPickupHeader: 'घरेलू ई-कचरा संकलन बुक करा',
    householdPickupBadge: 'घरेलू संकलन',
    aiPhotoScanner: 'एआय फोटो स्कॅनर (स्वयंचलित वर्गीकरण)',
    priceRangeTitle: 'अंदाजे बाजार भाव श्रेणी',
    donateToCsrLabel: 'पर्यावरण संस्थेला रक्कम दान करा (झाडे लावा)',
    confirmPickupBtn: 'खात्री करा व संकलन मागवा',
    traceabilityGuarantee: 'धातु मागोवा व सुरक्षितता हमी',
    traceabilityBadge: 'प्रमाणित साखळी',
    environmentalImpactHeader: 'पर्यावरण प्रभाव व लँडफिल डायव्हर्शन वही',
    personalImpactTitle: 'आपला वैयक्तिक लँडफिल डायव्हर्शन प्रभाव',
    downloadCertBtn: 'विल्हेवाट प्रमाणपत्र डाउनलोड करा',
    ewasteDiverted: 'ई-कचरा लँडफिलमध्ये जाण्यापासून वाचवला',
    carbonSaved: 'कार्बन उत्सर्जनात बचत',
    metalsRecycled: 'मौल्यवान धातू आणि तांबे पुनर्प्रक्रिया',
    csrCreditsEarned: 'सीएसआर ग्रीन क्रेडिट्स मिळवले',
    selfDropoffTitle: 'अधिकृत ई-कचरा संकलन केंद्रे',
    selfDropoffBadge: 'स्वतः जमा करण्याचा पर्याय',
    verifiedReceiptModalTitle: 'प्रमाणित डिजिटल हस्तांतरण पावती',
    mandiPriceBoardTitle: 'थेट ई-कचरा बाजार भाव फलक',
    digitalLotCreatorTitle: 'ई-कचरा डिजिटल लॉट तयार करा',
    lotCreationBadge: 'लॉट नोंदणी',
    lotCreatedSuccessTitle: 'लॉट यशस्वीरित्या नोंदवला!',
    uploadPhotoLabel: '१. भंगाराचा फोटो घ्या किंवा अपलोड करा',
    tapToSnapPhoto: 'कॅमेरा उघडा किंवा फोटो काढा',
    photoCapturedMsg: 'फोटो कॅप्चर व प्रमाणित (1080p)',
    approxWeightLabel: '३. अंदाजे वजन टाका (कि.ग्रा.)',
    minWeightNote: 'किमान ०.५ कि.ग्रा.',
    sellLotHere: 'या प्रकल्पाला लॉट विका',
    nearbyRecyclersTitle: 'जवळचे अधिकृत रीसायकलर व स्मेल्टर',
    handoverVoucherTitle: 'डिजिटल हस्तांतरण क्यूआर व्हाउचर',
    handoverVoucherBadge: 'डिजिटल हस्तांतरण',
    handoverStepsTitle: 'हस्तांतरणाचे ३ सोपे टप्पे',
    step1Weight: 'रीसायकलर गेटवर वजन करा',
    step1Desc: 'इलेक्ट्रॉनिक काट्यावर एकूण वजन नोंदवा.',
    step2Scan: 'हस्तांतरण क्यूआर स्कॅन करा',
    step2Desc: 'रीसायकलर ऑपरेटर आपल्या फोनवरून हा कोड स्कॅन करेल.',
    step3Pay: 'रोख किंवा पाकीट पेमेंट मिळवा',
    step3Desc: 'तातडीने रोख घ्या किंवा डिजिटल पाकिटात रक्कम मिळवा. पासबुकमध्ये नोंद.',
    formalizationBenefitTitle: 'खाण मंत्रालय औपचारिक प्रोत्साहन:',
    formalizationBenefitDesc: 'प्रत्येक प्रमाणित डिजिटल लॉट हस्तांतरणावर ₹५०० विशेष औपचारिक बोनस.',
    passbookTitle: 'भंगार संग्राहक रोख पासबुक',
    passbookBadge: 'रोख पासबुक',
    thDate: 'दिनांक',
    thDesc: 'तपशील',
    thParty: 'पक्ष',
    thMode: 'माध्यम',
    thAmount: 'रक्कम',
    thBalance: 'शिल्लक',
    thStamp: 'शिक्का',
    cashPaymentRule: 'रोख पेमेंट नियम: सर्व रोख व्यवहार डिजिटल स्वाक्षरीसह पासबुकमध्ये नोंदवले जातात.',
    downloadPassbookPdf: 'पासबुक पीडीएफ डाउनलोड करा',
    safetyCardsTitle: 'सुरक्षा नियम आणि घातक पद्धतींपासून संरक्षण',
    safetyBadge: 'सुरक्षा मार्गदर्शन',
    cpcbSafetyGuidelines: 'सीपीसीबी अनिवार्य ई-कचरा सुरक्षा मार्गदर्शक तत्त्वे',
    dosTitle: "काय करावे (DO'S):",
    dontsTitle: "कधीही करू नका (DON'TS):",
    safetyQuote: 'योग्य वर्गीकरणामुळे आरोग्याचे रक्षण होते आणि रीसायकलर ३५% जास्त मोबदला देतो.',
    valuePreservationTitle: 'जास्तीत जास्त कमाईसाठी सुरक्षित सुटे करण्याचे ४ नियम',
    valueBadge: 'मूल्यवर्धन मार्गदर्शिका',
    step1Plastic: 'टप्पा १: बाहेरील प्लास्टिक उघडा',
    step1PlasticDesc: 'स्क्रू न तोडता एबीएस प्लास्टिक कव्हर वेगळे करा (₹३८/कि.ग्रा. स्वतंत्र विक्री).',
    step2Pcb: 'टप्पा २: मदरबोर्ड अखंड ठेवा',
    step2PcbDesc: 'हाय-ग्रेड मदरबोर्डचे घटक सुरक्षित ठेवल्यास ₹६४०/कि.ग्रा. मिळतो.',
    step3Copper: 'टप्पा ३: तांब्याची तार थंड सोला',
    step3CopperDesc: 'मोटरमधील तांबे न जाळता वायर कटरने वेगळे करा (₹४८०/कि.ग्रा.).',
    step4Battery: 'टप्पा ४: बॅटऱ्या वेगळ्या पिशवीत ठेवा',
    step4BatteryDesc: 'शॉर्ट सर्किट किंवा आग टाळण्यासाठी लिथियम बॅटऱ्या कोरड्या पिशवीत ठेवा.',
    citizenPickupRequestsTitle: 'जवळच्या घरांकडून संकलन विनंत्या',
    citizenPickupsBadge: 'नागरिक संकलन',
    refreshBtn: 'ताजे करा',
    jobCompletedTitle: 'काम यशस्वीरित्या पूर्ण!',
    activeJobBadge: 'सुरू असलेले काम',
    callBtn: 'कॉल करा',
    verifyWeightTitle: 'अंतिम वजन तपासणी व नोंद:',
    completePickupBtn: 'संकलन पूर्ण करा व पावती द्या',
    livePickupsMapTitle: 'थेट ई-कचरा संकलन नकाशा',
    simulationControls: 'सिम्युलेशन नियंत्रणे',
    unitEconomicsBadge: 'आर्थिक नफा कॅल्क्युलेटर',
    platformSustainability: 'व्यासपीठ स्वावलंबन मॉडेल:',
    informalMarketLabel: 'सध्याची अनौपचारिक बाजारपेठ (यथास्थिती)',
    formalPlatformLabel: 'कबाडीवाला कनेक्ट व्यासपीठ (औपचारिक)',
    collectorKycTitle: 'संग्राहक केवायसी पडताळणी व ओळखपत्र',
    collectorKycBadge: 'केवायसी पडताळणी',
    kycVerified: 'प्रमाणित',
    kycPending: 'पडताळणी बाकी'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('dhatu_language');
    if (saved === 'hi' || saved === 'mr' || saved === 'en') return saved as Language;
    return 'en';
  });
  const [isSpeaking, setIsSpeaking] = useState(false);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('dhatu_language', lang);
  };

  const t = (key: string, fallback?: string): string => {
    return translations[language]?.[key] || translations.en[key] || fallback || key;
  };

  const speak = (text: string, langOverride?: Language) => {
    if (!('speechSynthesis' in window)) return;
    window.speechSynthesis.cancel();

    const targetLang = langOverride || language;
    const utterance = new SpeechSynthesisUtterance(text);
    if (targetLang === 'hi') utterance.lang = 'hi-IN';
    else if (targetLang === 'mr') utterance.lang = 'mr-IN';
    else utterance.lang = 'en-IN';

    utterance.rate = 0.92;
    utterance.onstart = () => setIsSpeaking(true);
    utterance.onend = () => setIsSpeaking(false);
    utterance.onerror = () => setIsSpeaking(false);

    window.speechSynthesis.speak(utterance);
  };

  const stopSpeaking = () => {
    if ('speechSynthesis' in window) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
    }
  };

  // Indian Number Format formatter (e.g. ₹1,20,000)
  const formatCurrency = (amount: number): string => {
    const rounded = Math.round(amount);
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
      maximumFractionDigits: 0
    }).format(rounded);
  };

  /**
   * Preserves scrap items being traded/sold STRICTLY IN ENGLISH.
   * As requested: "when i click on any language i want everything to be in that language except stuff being sold which must only be shown in english"
   */
  const preserveEnglishItemName = (name: string): string => {
    if (!name) return '';
    return KNOWN_ENGLISH_SCRAP_ITEMS[name] || name;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        speak,
        stopSpeaking,
        isSpeaking,
        formatCurrency,
        preserveEnglishItemName
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
